name: Buil and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # for mkdocs-git-revision-date-localized-plugin
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build site
        run: mkdocs build
      - name: Deploy to target branch
        uses: peaceiris/actions-gh-pages@v4  # push to branch: gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # directory of products built by MkDocs
          publish_branch: gh-pages  # target branch
      # - run: mkdocs gh-deploy --force
